---
title: "Business Analytics Lab"
description: |
  Welcome to the website. I hope you enjoy it!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

# News
| Contents                                         | Who  |  Date  |
| ------------------------------------------------ | ---- | ------ |
| Basic site structure of Lab web site has updated | Chad | May 21 |
| Supportive apps (wiki, lms) launched             | Chad | June 7 |


---

# Schedule
- [v] Book reading meeting / May 23, 5:00 PM / CBPM 223
- [v] Lab Meeting / June 7, 7:00 PM / CBPM 223
    - [Lab Presentation] Dynamic Documetation | Chad
    - [Book Reading] Sapience Part1(ch1,2,3,4)
    - [Lab Assignment] 
- [ ] Lab Meeting / June 13, 7:00 PM / CBPM C223
    - [Lab Presentation] A Brief Introduction to Research Article Structure | Chad
    - [Book Reading] Sapience Part2 (ch5,6,7,8)
    - [Lab Assignment] 
- [ ] Lab Meeting / June 15, 7:00 PM / CBPM C223
    - [Lab Presentation] Introduction to Bibliometrics| Chad
    - [Book Reading] Sapience Part3 (ch9,10,11,12,13)
    - [Lab Assignment] 
- [ ] Lab Meeting / June 19, 7:00 PM / CBPM C223
    - [Lab Presentation] A Brief Introduction to Research Typology and Flow | Chad
    - [Book Reading] Sapience Part4 (ch14,15,16,17,18,19,20)
    - [Lab Assignment] 
- [ ] Lab Meeting / June 22, 7:00 PM / CBPM C223
    - [Lab Presentation] Media Wiki: workflow and usages | V, Owen 
    - [Book Reading] Factfulness ch1,2,3
    - [Lab Assignment] 
- [ ] Lab Meeting / June 26, 7:00 PM / CBPM C223
    - [Lab Presentation]  Case Study Method | Jason, Allen
    - [Book Reading] Factfulness ch4,5,6
    - [Lab Assignment] 
- [ ] Lab Meeting / June 29, 7:00 PM / CBPM C223
    - [Lab Presentation]  Geographical Information System and Analysis | Claudia, Alina
    - [Book Reading] Factfulness ch7,8,9
    - [Lab Assignment] 
- [ ] Lab Meeting / June 29, 7:00 PM / CBPM C223
    - [Lab Presentation] Computational Social Science | Chad
    - [Book Reading] Factfulness ch10,11
    - [Lab Assignment] 

---

# Tasks

---

# Study